# Generated by Django 4.2.2 on 2023-06-17 06:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_userdetails_delete_userdetais'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userDetails',
            new_name='Profile',
        ),
    ]
